### ISSUE TITLE
Add an uncaught exception handler

### ISSUE THREAD

**Issue by danielcompton** [sethtrain/raven-clj#17]
Yeller provides a default uncaught exception handler which can be used to catch stuff that doesn't get caught by application code: https://github.com/yeller/yeller_java/blob/master/src/com/yellerapp/client/YellerHTTPClient.java#L10

**Comment by danielcompton** [comment]
Perhaps something like this, but with more fancy Sentry features:

```
(Thread/setDefaultUncaughtExceptionHandler
  (reify Thread$UncaughtExceptionHandler
    (uncaughtException [_ thread throwable]
      (raven/capture util/sentry-dsn
                     (raven-int/stacktrace {} throwable)))))
```

**Comment by martinklepsch** [comment]
👍  adding something like this as `install-uncaught-exception-handler!` or similar sounds like a great idea. I previously used a custom Timbre appender that logged errors to Sentry so I don't immediately have any code to contribute.

What do you think about opening a PR with that snippet wrapped in a function just so that there's something others can use as a foundation for further improvements?
